### ISSUE TITLE
configure: error: unrecognized options: --with-freetype, --with-jpeg

### ISSUE THREAD

**Issue by birdnestman** [getgrav/docker-grav#26]
Hello, I run into this issue. Any ideas why?

`configure: error: unrecognized options: --with-freetype, --with-jpeg
ERROR: Service 'grav' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     unzip     libfreetype6-dev     libjpeg62-turbo-dev     libpng-dev     libyaml-dev     libzip4     libzip-dev     zlib1g-dev     libicu-dev     g++     git     cron     vim     && docker-php-ext-install opcache     && docker-php-ext-configure intl     && docker-php-ext-install intl     && docker-php-ext-configure gd --with-freetype --with-jpeg     && docker-php-ext-install -j$(nproc) gd     && docker-php-ext-install zip     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1`

**Comment by frunika** [comment]
Which php version / base image do you use?

**Comment by birdnestman** [comment]
Hi @frunika 
I used exactly the Dockerfile from this repo. I'm using OSX. I've built it with `docker-compose up`
I removed the options and changed the docker-compose to the follwoing:
```
version: '3.0'

services:
  grav:
    container_name: truetsch_grav
    build: ./
    ports:
      - 8090:80
    volumes:
      - ./:/var/www/html
```

Now it seems to work.
